Insert INTO CATEGORIES (NAME, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES('shopping', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

Insert INTO CATEGORIES (NAME, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES('private expenses', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

Insert INTO CATEGORIES (NAME, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES('bank loan', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());